# Type de recherche
#   - "Publications" : recherche de publications & brevets par identifiant Scopus
#   - "Profils"      : recherche de profils d'auteurs par noms, pour une éventuelle
#                      recherche de publications par identifiants Scopus
# NB: Tous les fichiers spécifiés sont lus/écrits dans le même répertoire que ce fichier .toml
#
#search_type = "Profils"
search_type = "Publications"

# Fichier Excel d'entrée et nom du feuillet contenant les information des auteur.e.s
# (colonnes "Nom", "Prénom", ainsi que "Scopus ID" pour les recherches de publications)
in_excel_file = "Liste chercheurs-membres.xlsx"
in_excel_file_author_sheet = "Membres"

# Gamme d'années pour la recherche de publications (ignoré pour la recherche de profils)
pub_year_first = 2025
pub_year_last = 2025

# Noms d'institutions/affiliations considérées commme "locales" avec leurs identifiants Scopus,
# pour valider les profils d'auteurs dans les recherches
local_affiliations = [
    ["Université de Sherbrooke", "60011832"],
    ["3IT", "60190927"],
    ["Institut interdisciplinaire d'innovation technologique", "60190927"],
    ["LN2", "60108180"],
    ["Laboratoire nanotechnologies et nanosystèmes", "60108180"]
]

# SCOPUS : Paires de descriptifs (au choix de l'usager) et codes à deux lettres Scopus
# correspondants pour la recherche par publications.
# Codes Scopus disponibles :
#   Article-ar / Abstract Report-ab / Book-bk / Book Chapter-ch / Conference Paper-cp /
#   Conference Review-cr / Data Paper-dp / Editorial-ed / Erratum-er / Letter-le /
#   Multimedia-mm / Note-no / Report-rp / Retracted-tb / Review-re / Short Survey-sh
publication_types_scopus = [["Articles", "ar"], ["Confs", "cp"], ["Absracts", "ab"], ["Livres", "bk"],
    ["Chap. de livres", "ch"], ["Lettres", "le"], ["Rapports", "rp"]]

# SCOPUS : Intervalle de mise à jour (en nombre de jours) de la copie locale de la base de
# données. Une recherche en ligne dans Scopus prend beaucoup de temps, les résultats sont
# sauvegardés dans une base de données locale pour éviter de refaire la recherche
# en ligne à chaque fois. Cette base de données locale est mise à jour à
# intervalles réguliers (valeur par défaut = 0, i.e. mise à jour à chaque recherche).
scopus_database_refresh_days = 7

# BREVETS : Activer/désactiver (true/false) la recherche de brevets USPTO et ESPACENET (INPADOC)
# 1) La recherche de brevets dans INPADOC est préférable à l'USPTO parce que les brevets
#    sont groupés par familles, ce qui permet notamment de retenir uniquement les
#    premiers dépots et octrois de brevets pour une invention et éviter les redondances
#    (brevets dans plusieurs pays, multiples numéros de brevets pour une même invention
#    reliés à des variations mineures comme des changements aux revendications,
#    des modifications cléricales, etc.)
# 2) Si un nom de fichier est spécifié par "espacenet_patent_search_results_file", la recherche
#    dans espacenet est faite à partir de ce fichier, sinon une nouvelle recherche est faite
#    en ligne et les résultats sont sauvegardés dans le fichier "espacenet_INPADOC_results_YYYYMMDD.xlsx"
#    où YYYYMMDD est la date de la recherche.
espacenet_patent_search = true
espacenet_patent_search_results_file = "espacenet_search_results_20251023.xlsx"
