# Type de recherche
#   - "Publications" : recherche de publications & brevets par identifiant Scopus
#   - "Profils"      : recherche de profils d'auteurs par noms, pour une éventuelle
#                      recherche de publications par identifiants Scopus
# NB: Tous les fichiers spécifiés sont lus/écrits dans le même répertoire que ce fichier .toml
#
#search_type = "Profils"
search_type = "Publications"

# Fichier Excel d'entrée et nom du feuillet contenant les information des auteur.e.s
# (colonnes "Nom", "Prénom", ainsi que "Scopus ID" pour les recherches de publications)
in_excel_file = "Liste chercheurs-membres.xlsx"
in_excel_file_author_sheet = "Membres"

# Gamme d'années pour la recherche de publications (ignoré pour la recherche de profils)
pub_year_first = 2024
pub_year_last = 2025

# Activer/désactiver l'extraction différentielle Scopus relativement au 1er du mois précédant,
# spécification de la liste d'envois de courriels de confirmation, où la première adresse
# email reçoit aussi le fichier log de l'exécution.
extract_scopus_diff = true
extract_scopus_diff_confirmation_emails = [
    "Paul.Charette@USherbrooke.ca",
    "francois.z.thibeault@usherbrooke.ca",
    "denis.machon@usherbrooke.ca",
    "catherine.labrecque@usherbrooke.ca",
    "christelle.hauchard@usherbrooke.ca",
]
#extract_scopus_diff_confirmation_emails = [
#    "Paul.Charette@USherbrooke.ca",
#    "pgcharette@gmail.com",
#]

# Noms d'institutions/affiliations considérées commme "locales" avec leurs identifiants Scopus,
# pour valider les profils d'auteurs dans les recherches
local_affiliations = [
    ["Université de Sherbrooke", "60011832"],
    ["3IT", "60190927"],
    ["Institut interdisciplinaire d'innovation technologique", "60190927"],
    ["LN2", "60108180"],
    ["Laboratoire nanotechnologies et nanosystèmes", "60108180"]
]

# SCOPUS : Paires de descriptifs (au choix de l'usager) et codes à deux lettres Scopus
# correspondants pour la recherche par publications.
# Codes Scopus disponibles :
#   Article-ar / Abstract Report-ab / Book-bk / Book Chapter-ch / Conference Paper-cp /
#   Conference Review-cr / Data Paper-dp / Editorial-ed / Erratum-er / Letter-le /
#   Multimedia-mm / Note-no / Report-rp / Retracted-tb / Review-re / Short Survey-sh
publication_types = [["Articles", "ar"], ["Confs", "cp"], ["Absracts", "ab"], ["Livres", "bk"],
    ["Chap. de livres", "ch"], ["Lettres", "le"], ["Rapports", "rp"]]

# SCOPUS : Intervalle de mise à jour (en nombre de jours) de la copie locale de la base de
# données. Une recherche en ligne dans Scopus prend beaucoup de temps, les résultats sont
# sauvegardés dans une base de données locale pour éviter de refaire la recherche
# en ligne à chaque fois. Cette base de données locale est mise à jour à
# intervalles réguliers (valeur par défaut = 0, i.e. mise à jour à chaque recherche).
scopus_database_refresh_days = 0
